name: odrenv
channels:
  - pytorch
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python
  - pytorch=1.9.*
  - torchvision=0.10.*
  - pytorch-lightning=1.4.4
  - cudatoolkit=11.1.1
  - pillow=8.3.1
  - matplotlib=3.3.4
  - numpy=1.21.2
  - pandas=1.2.4
  - jupyter=1.0.0
  - pycocotools=2.0
  - imgaug=0.4.0
  - albumentations=1.0.3
  - plotly=5.2.2
  - optuna=2.9.1
  - python-kaleido=0.0.3
